### PR TITLE
Fix issue #33

### PR DESCRIPTION
**Pull request by MagnusKoudahl**
Remove typecheck on x_hat in function "approximate" for nonlinear node.

### CODE REVIEW

**Comment by bauglir** [comment]
Removing type indications should never be the 'solution' if you ask me.

There may be some deeper reason here that I don't understand for removing the input signature. But I would assume you still expect either a number or an array of numbers to be specified. In other words, changing the type signature to
```julia
Union{T, Vector{T}} where T <: Number
```
should be the actual fix.

**Comment by MagnusKoudahl** [comment]
I'm inclined to agree. It's better than just removing them!

However approximate is only used to feed input to user specified functions g and J_g. I can envision a case where a user wants to do complicated custom processing inside the node and would get caught up on this error.
I think a case can be made that the user should be able to do whatever they want with their custom functions as long as the output integrates nicely with the rest of FL. In which case the error should come from somewhere else.

**Comment by bauglir** [comment]
That makes sense. Although, given the rest of the processing/mathematical operations that occur in this function does it even make sense to allow any other type then numbers or arrays of numbers?

I'm wondering whether it would be possible to do some type checking/restrictions on the function signatures, but I'm relatively sure that's not possible in Julia. Could still do return value typeasserts though. But I'll leave that up to you.

**Comment by MagnusKoudahl** [comment]
Good point. I can't find an immediate way to pass anything else given that inputs come from the rest of the graph. It might still be possible if one is crafty and dedicated though.

I'll update with your suggestion. If it turns out that users find a way to pass flags/custom types/other stuff we may want to revisit this.

**Pull request merged**
