### PR TITLE
Add demo of 2d Gaussian inference.

### PR DESCRIPTION
**Pull request by murphyk**
Reproduce the example from "Machine learning: a probabilistic perspective"
(Murphy, 2012) fig 4.13.

### CODE REVIEW

**Comment by murphyk** [comment]
This regenerates the plots shown below.
http://people.cs.ubc.ca/~murphyk/MLbook/figReport-16-Aug-2012/pdfFigures/gauss2dupdatePostSubplot.pdf

**Comment by ThijsvdLaar** [comment]
Thank you for these demos, it would be great to incorporate them in the current demos folder. If you don't mind I'll try to restructure them (and in the meantime revise some of our own demos) in order to make them fit better with the current flow.

**Comment by murphyk** [comment]
Sure. They do need some restructuring, and optionally rewriting as a notebook, but I thought it's better to have some multivariate demos added ASAP to help other users.

**Comment by ThijsvdLaar** [comment]
@murphyk I converted the Bayesian inference and Kalman smoother demo to Jupyter notebooks; please let me know if you agree with this setup.

**Comment by murphyk** [comment]
LGTM

**Pull request merged**
