### PR TITLE
Multivariate nonlinear function of non Gaussian inputs

### PR DESCRIPTION
**Pull request by semihakbayrak**
This implementation allows users to define nonlinear relations between multiple random variables.

### CODE REVIEW

**Review by ThijsvdLaar — CHANGES_REQUESTED** [review]
I noticed that in the message updates, the input `Vararg{Message{<:Gaussian, V}}` are still forced to be of the same `V<:VariateType`. I think they should be `Vararg{Message{<:Gaussian, <:VariateType}}` instead. I'm missing tests, which would have caught this issue. Also the new updates are not tested.

**Comment by ivan-bocharov** [comment]
@ThijsvdLaar thanks for the review. You are correct, current implementation restricts the input types too much. I will also address the rule applicability in corresponding `isApplicable` methods (and add tests).

**Review by ThijsvdLaar — APPROVED** [review]
Thanks for the fix, looks good to go

**Comment by ivan-bocharov** [comment]
Thanks for your review, Thijs!

**Pull request merged**
