### PR TITLE
fix bug - removePrefix()

### PR DESCRIPTION
**Pull request by bartvanerp**
Allows for parameterized custom nodes with custom types.

### CODE REVIEW

**Comment by ThijsvdLaar** [comment]
Thanks for catching this. I started refactoring and came up with a more general recursive implementation:
```jl
function removePrefix(T::DataType)
    main_type_str = string(nameof(T)) # Strip leading module names and convert T to a string
    param_types = T.parameters # Find parameterized types of T
    if isempty(param_types) # If T is not parameterized further
        return main_type_str # Stop-condition, return main name
    else
        # Recursively build a vector of strings for the parameter types 
        param_type_strs = []
        for param_type in param_types
            push!(param_type_strs, removePrefix(param_type)) # Recursive call
        end
        param_type_str = join(param_type_strs, ", ") # Join the constructed vector to a comma-separated string

        return "$main_type_str{$param_type_str}" # Construct the parameterized type string
    end
end
```
This could be tested for a nested definition, like:
```jl
module Foo

struct Baz
    f::Int64
end

struct Bar{T}
    f::T
end

struct Bak{T, K}
    f::T
    g::K
end

end

baz = Foo.Baz(1)
bar = Foo.Bar(baz)
bak = Foo.Bak(bar, bar)

removePrefix(typeof(baz))
removePrefix(typeof(bar))
removePrefix(typeof(bak))
```

**Comment by bartvanerp** [comment]
Thanks for the suggestion Thijs. I changed the `removePrefix()` function to your suggestion. As a result from this change 6 tests failed, each having to do with the string comparison of terms involving `Message`.  Due to the change of `removePrefix()`, the generated source code included strings with `ForneyLab.Message` instead of the original `Message`. To copy with this, I updated the tests. I am not sure whether these changes in the tests are desirable or whether changes to 
`removePrefix()` are preferred.

**Comment by ThijsvdLaar** [comment]
Thanks for the implementation, I did not think about how this would affect the `Message` code generation. However, generating `ForneyLab.Message` seems rather superfluous to me, so I think it would be better to update the `removePrefix()` instead.

**Comment by bartvanerp** [comment]
The proposed function originally had issues with the following:
The input argument type was converted from `::Type` to `::DataType`, which excluded the `::UnionAll` type that is used for the `inbound.dist_or_msg` attribute. 
Therefore the new function was not called, but instead the `::Any` function was called which just return the input argument. 

In order to solve this, the original function with input `::Type` was added back to catch the `::UnionAll` cases.

The latest commits revert the changes to the tests and reintroduce the original function as a backup to the new function.

**Review by ThijsvdLaar — APPROVED** [review]

**Pull request merged**
