### PR TITLE
Natural parameter distributions

### PR DESCRIPTION
**Pull request by ThijsvdLaar**
Implement natural parameter definitions from https://github.com/semihakbayrak/ForneyLab.jl/tree/CVI Additionaly:
- Refactor definitions
- Add tests

### CODE REVIEW

**Comment by albertpod** [comment]
Looks good. But why do we add this to FL?

**Comment by ThijsvdLaar** [comment]
Great, thanks; it's some prep work for natural gradient descent. I tried to refactor Semih's work (#183) in smaller chunks that fit my head.

**Comment by semihakbayrak** [comment]
Thanks @ThijsvdLaar for your contribution! I liked how you implemented StandardDist function directly with distribution and variate types rather than their instances. For the logpdf function of exponential family (EF) of distributions, how about implementing just one function: log(h(x)) + transpose(ϕ(x))*η - logNormalizer(dist,η) in probability_distributions.jl file instead of defining them separately for the distributions? We can then implement components of logpdf separately for each distribution, as it has been done for logNormalizer, so as to use them in other applications when necessary. For example, I can imagine that sufficient statistics is useful in many applications and would be nice to have this function in FL.

**Comment by ThijsvdLaar** [comment]
I agree that implementing a single log-pdf function is more beautiful from a mathematical point of view, but from a coding point-of view it would add complexity. We would have to define `h` and `\phi` functions for each distribution type, which are not used anywhere else outside of the log-pdf function. Since there is currently no case for reuse of these statistics, I would prefer the more direct approach.

**Review by semihakbayrak — APPROVED** [review]
Thanks Thijs! Ready to be merged, in my opinion.

**Pull request merged**
