### PR TITLE
v0.7/v1.0 compatibility

### PR DESCRIPTION
**Pull request by ivan-bocharov**
This pull request ports ForneyLab codebase to Julia v0.7/v1.0.

You can try it out in Julia 0.7/1.0 using following command:

`] add git@github.com:ivan-bocharov/ForneyLab.jl.git#v1-compatibility`

Notable changes in Julia:

- New package manager ([Pkg](https://docs.julialang.org/en/v1/stdlib/Pkg/index.html)).
- The syntax for parametric methods, `function f{T}(x::T)`, has been changed to function `f(x::T) where {T}`.
- Uninitialized Array constructors of the form `Array[{T,N}](shape...)` have been deprecated in favor of equivalents accepting `undef` as their first argument, as in `Array[{T,N}](undef, shape...)`. For example, `Vector{Message}(3)` is now `Vector{Message}(undef, 3)`, etc.
- A lot of functions were moved from `Base` to corresponding specialized package. For example, functions `diag`, `det`, `tr` (formerly `trace`) are now a part of `LinearAlgebra` package from standard library.

For other changes in language please refer to [v0.7 release notes](https://github.com/JuliaLang/julia/blob/master/HISTORY.md#julia-v070-release-notes).

### CODE REVIEW

**Comment by marcocox** [comment]
Great, thanks. Can you update `.travis.yml` with the correct Julia version to fix the  CI tests?

**Comment by marcocox** [comment]
Same for `REQUIRE`.

**Comment by ThijsvdLaar** [comment]
Great work! I noticed that the `VERSION` file still specifies `0.8.0`. I don't believe Pkg3 uses `VERSION` and `REQUIRE` anymore, right? So we might as well remove these and directly focus the whole thing on Pkg3 and julia 1.0?

**Comment by ivan-bocharov** [comment]
I don't think `VERSION` and `REQUIRE` files are needed as of `Pkg(3)` release and are deprecated in favour of `Project.toml` file. However, I have left the `REQUIRE` file in the repo because of the [following issue](https://github.com/JuliaGraphics/Colors.jl/issues/322) in Colors.jl repo. CI Bot that performs checks when the package is published doesn't work with `Project.toml` yet.

**Pull request merged**
